spec-version: 0.35.1
name: myxmonad
version: 0.1.0.0
ghc-options:
- -Wall
- -threaded
language: GHC2021
default-extensions:
- OverloadedStrings
dependencies:
- base >= 4.12 && < 5
- xmonad
- xmonad-contrib
library:
  source-dirs: lib
  generated-other-modules: Paths_myxmonad
  dependencies:
  - aeson
  - bytestring
  - containers
  - dbus
  - libnotify
  - process
  - split
  - transformers
executables:
  cpanel:
    source-dirs: cpanel
    main: main.hs
    dependencies:
    - myxmonad
  xmonad:
    source-dirs: app
    main: xmonad.hs
    dependencies:
    - myxmonad
    - east-gate
  powerwatch:
    source-dirs: app
    main: powerwatch.hs
    dependencies:
    - myxmonad
