spec-version: 0.35.1
name: myxmonad
version: 0.1.0.0

ghc-options:
  - -Wall

language: GHC2021
default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.12 && < 5
  - xmonad
  - xmonad-contrib

library:
  source-dirs: lib
  generated-other-modules: Paths_myxmonad
  dependencies:
    - libnotify
    - split

executables:
  cpanel:
    source-dirs: app
    main: cpanel.hs
    dependencies:
      myxmonad
  xmonad:
    source-dirs: app
    main: xmonad.hs
    dependencies:
      myxmonad
